#!/usr/bin/env node
/**
 * phase 34 일회성 가드레일 — 바뀐 것이 개념 배열 순서뿐인지 본다.
 *
 * 사용법: node phases/34-service-block-order/verify-order.mjs <step>
 *
 * 착수 시점(develop 127b6b1)의 해시를 박아 둔 검사다. 저장소 공용 테스트로 올리지 마라 —
 * 이 phase가 끝난 뒤 콘텐츠를 정당하게 고치면 영구히 실패한다. 이 phase 안에서만 쓴다.
 *
 * | 검사 | 무엇을 보장하나 |
 * |---|---|
 * | questions.json 해시 | 문항·보기·해설·answerIndex·문항 배열이 한 글자도 안 바뀌었다 |
 * | topics.json 내용 해시(주제 안 개념을 id로 정렬해서) | 개념 id·name·summary·paragraphs, 개념의 주제 소속, 주제 메타데이터·주제 순서가 그대로다 |
 * | topics.json 줄 다중집합 해시(끝 쉼표를 떼고 정렬) | 바뀐 것이 줄 자리와 끝 쉼표뿐이다 — 재직렬화·글자 수정이 없다 |
 * | 개념 618개·id 중복 0·주제별 id 집합 | 누락·중복이 없다 |
 * | 순서가 바뀐 주제 | 정확히 이 step까지 명세된 주제들이다 |
 * | 서비스 왕복 | 순서가 바뀐 주제마다 before → after를 찍고, after가 0이 아니면 실패한다 |
 * | topics-baseline.json 내용 해시·줄 다중집합 해시 | 스냅샷도 개념 항목 순서만 바뀌었다 |
 * | 스냅샷 순서 = topics.json 순서 | 두 파일의 개념 순서가 같다 |
 *
 * 왕복: 한 블록을 떠났다가 그 블록으로 돌아오는 횟수. 블록 이름이 '*'로 시작하는 개념은
 * 두 블록 이상을 가르는 비교 개념이라 세지 않는다.
 */
import { readFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const read = (p) => readFileSync(join(ROOT, p), 'utf8')
const sha = (s) => createHash('sha256').update(s).digest('hex')
const byId = (a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0)
const lineMultiset = (s) => sha(s.split('\n').map((l) => l.replace(/,$/, '')).sort().join('\n'))

const BASE = {
  content: '8e67f78986176697e83ea7d502befd6fc562112de7458937924cf9e6011511eb',
  questions: 'aadc1894b3eb2d9211159ef346057bf24510ba534b78ccade4d40bf018343f54',
  topicsLines: '1dd79d90c0311f5d6ca7daf11580f0fc7fe01c3bbc2fe583d8ea3feef952b023',
  baselineCanon: '1773a4125399a405ad55f0f1b1836e77bd98559a15fcb4bcc7b7799327584bf0',
  baselineLines: '5e478fedda7719a02762efab1d3901e0c95cd8884cc1539a4ea8d8b1672dafb7',
}

/** step마다 새로 재정렬하는 주제. 순서가 바뀐 주제는 0..step의 합집합이어야 한다. */
const STEPS = [
  [],
  ["data-transfer-services", "sqs-sns-eventbridge", "efs-fsx", "cloudfront-global-accelerator", "secrets-encryption"],
  ["s3-encryption-batch", "ebs-instance-store", "elasticache-purpose-built-db", "elastic-load-balancing", "ecs-eks-fargate", "api-gateway-step-functions"],
  ["vpc-networking", "security-groups-nacl", "hybrid-connectivity", "emr-glue-athena", "kinesis-streaming", "redshift-opensearch-quicksight", "cloudwatch-xray"],
  ["waf-shield", "guardduty-macie-inspector", "identity-federation", "organizations-cloudtrail-config", "cost-management"],
  ["s3-versioning-lifecycle", "s3-access-control", "storage-gateway-migration", "rds-storage-features", "aurora", "dynamodb", "ec2-autoscaling", "lambda"],
  ["backup-disaster-recovery", "route53", "iam-permissions", "governance-iac", "systems-manager", "ai-ml-services"],
  [],
]

/** 착수 시점의 개념 순서와 각 개념의 블록. */
const ORIGINAL = {
  "aws-core-services": [["aws-core-services.ec2", "ec2"], ["aws-core-services.rds", "rds"], ["aws-core-services.s3", "s3"], ["aws-core-services.route-53", "r53"], ["aws-core-services.dns", "dns"], ["aws-core-services.elb", "elb"], ["aws-core-services.cloudfront", "cf"], ["aws-core-services.lambda", "lambda"], ["aws-core-services.region", "region"], ["aws-core-services.availability", "avail"], ["aws-core-services.availability-zone", "az"], ["aws-core-services.multi-az", "maz"], ["aws-core-services.single-az", "saz"], ["aws-core-services.on-premise", "onprem"], ["aws-core-services.migration", "mig"], ["aws-core-services.exam-heuristics", "*h"], ["aws-core-services.exponential-backoff-retry", "*h"], ["aws-core-services.blob-offload-to-s3", "*h"]],
  "s3-storage-classes": [["s3-storage-classes.standard", "std"], ["s3-storage-classes.intelligent-tiering", "it"], ["s3-storage-classes.standard-ia", "sia"], ["s3-storage-classes.one-zone-ia", "ozia"], ["s3-storage-classes.glacier-instant-retrieval", "gir"], ["s3-storage-classes.glacier-flexible-retrieval", "gfr"], ["s3-storage-classes.glacier-deep-archive", "gda"], ["s3-storage-classes.s3-express-one-zone", "xoz"], ["s3-storage-classes.retrieval-time", "*"], ["s3-storage-classes.glacier-or-standard-ia", "*"], ["s3-storage-classes.glacier-flexible-retrieval-standard-time", "*"], ["s3-storage-classes.glacier-flexible-retrieval-expedited", "*"], ["s3-storage-classes.s3-storage-class-cost-order", "*"], ["s3-storage-classes.lifecycle-vs-intelligent-tiering", "*"], ["s3-storage-classes.s3-storage-class-analysis", "ana"], ["s3-storage-classes.s3-retrieval-fee-by-class", "*"], ["s3-storage-classes.intelligent-tiering-monitoring-fee", "*"]],
  "s3-versioning-lifecycle": [["s3-versioning-lifecycle.versioning", "ver"], ["s3-versioning-lifecycle.object-lock", "lock"], ["s3-versioning-lifecycle.lifecycle-policy", "lc"], ["s3-versioning-lifecycle.event-notification", "notif"], ["s3-versioning-lifecycle.s3-replication", "repl"], ["s3-versioning-lifecycle.s3-same-region-replication", "repl"], ["s3-versioning-lifecycle.s3-replication-time-control", "repl"], ["s3-versioning-lifecycle.s3-replication-cross-account-kms", "repl"], ["s3-versioning-lifecycle.object-lock-prerequisites", "lock"], ["s3-versioning-lifecycle.s3-lifecycle-rules-and-size-filter", "lc"]],
  "s3-encryption-batch": [["s3-encryption-batch.sse", "enc"], ["s3-encryption-batch.sse-types", "enc"], ["s3-encryption-batch.client-side-encryption", "enc"], ["s3-encryption-batch.batch-operations", "batch"], ["s3-encryption-batch.s3-inventory-report", "batch"], ["s3-encryption-batch.s3-object-lambda", "ol"], ["s3-encryption-batch.envelope-encryption", "enc"], ["s3-encryption-batch.sse-kms-audit-trail", "enc"], ["s3-encryption-batch.batch-copy-vs-replication", "batch"], ["s3-encryption-batch.s3-batch-operations-lambda-invoke", "batch"], ["s3-encryption-batch.sse-kms-cost", "enc"], ["s3-encryption-batch.sse-c-no-rotation-or-audit", "enc"], ["s3-encryption-batch.s3-secure-transport-condition", "enc"]],
  "s3-access-control": [["s3-access-control.s3-cross-account-bucket-policy", "bp"], ["s3-access-control.s3-presigned-url", "psu"], ["s3-access-control.s3-access-grants", "ag"], ["s3-access-control.s3-access-point", "ap"], ["s3-access-control.s3-multi-region-access-point", "ap"], ["s3-access-control.s3-storage-lens", "lens"], ["s3-access-control.s3-cors-not-authorization", "cors"], ["s3-access-control.s3-requester-pays", "rp"], ["s3-access-control.s3-storage-lens-advanced-activity-metrics", "lens"], ["s3-access-control.s3-account-level-public-access-block", "bpa"], ["s3-access-control.block-public-access-allows-explicit-grants", "bpa"], ["s3-access-control.s3-bucket-policy-source-vpc-condition", "bp"], ["s3-access-control.s3-website-endpoint-no-https", "web"]],
  "ebs-instance-store": [["ebs-instance-store.ebs", "ebs"], ["ebs-instance-store.ebs-elastic-volumes", "ebs"], ["ebs-instance-store.instance-store", "is"], ["ebs-instance-store.cluster-placement-group", "pg"], ["ebs-instance-store.elastic-fabric-adapter", "efa"], ["ebs-instance-store.ebs-volume-type-names", "ebs"], ["ebs-instance-store.gp3-iops-independent-of-size", "ebs"], ["ebs-instance-store.spread-placement-group", "pg"], ["ebs-instance-store.io2-block-express-iops-ceiling", "ebs"], ["ebs-instance-store.ebs-encryption-by-default", "ebs"], ["ebs-instance-store.ebs-encryption-performance", "ebs"], ["ebs-instance-store.ebs-recycle-bin", "snap"], ["ebs-instance-store.ebs-snapshot-block-public-access", "snap"], ["ebs-instance-store.data-lifecycle-manager", "snap"], ["ebs-instance-store.ebs-fast-snapshot-restore", "snap"]],
  "efs-fsx": [["efs-fsx.efs", "efs"], ["efs-fsx.efs-lifecycle-management", "efs"], ["efs-fsx.fsx", "fsx"], ["efs-fsx.fsx-windows-file-server", "win"], ["efs-fsx.fsx-for-lustre", "lus"], ["efs-fsx.fsx-file-gateway", "fgw"], ["efs-fsx.efs-throughput-modes", "efs"], ["efs-fsx.efs-elastic-throughput", "efs"], ["efs-fsx.efs-performance-modes", "efs"], ["efs-fsx.efs-one-zone", "efs"], ["efs-fsx.efs-posix-permissions", "efs"], ["efs-fsx.fsx-lustre-sub-millisecond-latency", "lus"], ["efs-fsx.fsx-lustre-persistent-deployment", "lus"], ["efs-fsx.fsx-ontap-multi-az", "ontap"], ["efs-fsx.fsx-ontap-multi-protocol-tiering", "ontap"], ["efs-fsx.fsx-ontap-iscsi-block", "ontap"], ["efs-fsx.fsx-ontap-snapmirror", "ontap"], ["efs-fsx.sql-server-always-on-shared-storage", "win"], ["efs-fsx.efs-ia-file-size-threshold", "efs"], ["efs-fsx.efs-lifecycle-transition-to-primary", "efs"], ["efs-fsx.efs-mount-target-per-az", "efs"], ["efs-fsx.efs-cross-account-mount", "efs"], ["efs-fsx.efs-replication-one-way", "efs"], ["efs-fsx.fsx-windows-storage-auto-scaling", "win"], ["efs-fsx.fsx-lustre-s3-data-repository-association", "lus"]],
  "data-transfer-services": [["data-transfer-services.datasync", "ds"], ["data-transfer-services.snowball-edge", "sb"], ["data-transfer-services.snowball-edge-compute", "sb"], ["data-transfer-services.transfer-family", "tf"], ["data-transfer-services.transfer-family-workflow", "tf"], ["data-transfer-services.s3-transfer-acceleration", "s3"], ["data-transfer-services.transfer-deadline-vs-bandwidth", "sb"], ["data-transfer-services.file-gateway-vs-datasync-continuous", "ds"], ["data-transfer-services.transfer-family-custom-hostname", "tf"], ["data-transfer-services.transfer-family-directory-service-identity-provider", "tf"], ["data-transfer-services.transfer-family-service-managed-users", "tf"], ["data-transfer-services.datasync-scope-limits", "ds"], ["data-transfer-services.datasync-in-transit-encryption", "ds"], ["data-transfer-services.datasync-manifest", "ds"], ["data-transfer-services.datasync-transfer-mode", "ds"], ["data-transfer-services.datasync-task-status-event", "ds"], ["data-transfer-services.transfer-family-workflow-actions", "tf"], ["data-transfer-services.transfer-family-structured-logging", "tf"], ["data-transfer-services.s3-multipart-upload", "s3"]],
  "storage-gateway-migration": [["storage-gateway-migration.storage-gateway", "sg"], ["storage-gateway-migration.dms-sct", "dms"], ["storage-gateway-migration.application-migration-service", "mgn"], ["storage-gateway-migration.storage-gateway-gateway-types", "sg"], ["storage-gateway-migration.storage-gateway-volume-modes", "sg"], ["storage-gateway-migration.tape-gateway-archive-tiers", "sg"], ["storage-gateway-migration.dms-full-load-and-cdc-task", "dms"]],
  "rds-storage-features": [["rds-storage-features.rds", "base"], ["rds-storage-features.storage-types", "stor"], ["rds-storage-features.features", "*feat"], ["rds-storage-features.rds-blue-green-deployment", "bg"], ["rds-storage-features.rds-custom", "custom"], ["rds-storage-features.rds-iam-database-authentication", "iam"], ["rds-storage-features.rds-encryption-scope-and-in-transit", "enc"], ["rds-storage-features.storage-type-names", "stor"], ["rds-storage-features.multi-az-standby-limits", "maz"], ["rds-storage-features.rds-multi-az-db-cluster", "maz"], ["rds-storage-features.read-replica-vs-cache", "rr"], ["rds-storage-features.connection-issue-heuristic", "proxy"], ["rds-storage-features.rds-proxy-failover", "proxy"], ["rds-storage-features.rds-snapshot-cross-region-copy", "bak"], ["rds-storage-features.automated-backup-retention", "bak"], ["rds-storage-features.rds-manual-snapshot-retention", "bak"], ["rds-storage-features.rds-pitr-transaction-log-interval", "bak"], ["rds-storage-features.rds-multi-az-failover-rto", "maz"], ["rds-storage-features.rds-stop-instance-restart", "stop"], ["rds-storage-features.rds-encrypt-existing-instance", "enc"], ["rds-storage-features.rds-custom-byol", "custom"]],
  "aurora": [["aurora.aurora", "base"], ["aurora.aurora-serverless-v2", "sls"], ["aurora.aurora-reader-endpoint", "rep"], ["aurora.aurora-endpoint-types", "rep"], ["aurora.aurora-replica-auto-scaling", "rep"], ["aurora.babelfish", "eng"], ["aurora.aurora-pgvector", "eng"], ["aurora.aurora-select-into-outfile-s3", "eng"], ["aurora.aurora-global-database-dr-targets", "glob"], ["aurora.aurora-cross-region-read-replica", "glob"], ["aurora.aurora-continuous-backup-rpo", "bak"], ["aurora.aurora-clone", "bak"], ["aurora.aurora-storage-configurations", "stor"], ["aurora.sql-server-license-cost", "eng"], ["aurora.aurora-zdr-and-activity-streams", "misc"], ["aurora.aurora-global-database-write-region", "glob"], ["aurora.aurora-serverless-max-acu", "sls"], ["aurora.read-replica-no-schema-change", "rep"]],
  "dynamodb": [["dynamodb.dynamodb", "base"], ["dynamodb.dynamodb-single-digit-latency", "base"], ["dynamodb.dynamodb-streams", "str"], ["dynamodb.dynamodb-global-tables", "glob"], ["dynamodb.dynamodb-ttl", "ttl"], ["dynamodb.dynamodb-global-secondary-index", "gsi"], ["dynamodb.dynamodb-capacity-modes", "cap"], ["dynamodb.dynamodb-auto-scaling-target-utilization", "cap"], ["dynamodb.dynamodb-read-consistency", "cons"], ["dynamodb.dynamodb-s3-export-vs-streams", "exp"], ["dynamodb.dynamodb-incremental-export", "exp"], ["dynamodb.dynamodb-export-no-read-capacity", "exp"], ["dynamodb.dynamodb-pitr", "exp"], ["dynamodb.dynamodb-export-requires-pitr", "exp"], ["dynamodb.dynamodb-item-size-limit", "item"], ["dynamodb.dynamodb-ttl-deletion-delay", "ttl"], ["dynamodb.dynamodb-streams-retention-24h", "str"], ["dynamodb.dynamodb-streams-batch-size", "str"]],
  "elasticache-purpose-built-db": [["elasticache-purpose-built-db.elasticache", "ec"], ["elasticache-purpose-built-db.documentdb", "docdb"], ["elasticache-purpose-built-db.neptune", "nep"], ["elasticache-purpose-built-db.neptune-streams", "nep"], ["elasticache-purpose-built-db.qldb", "qldb"], ["elasticache-purpose-built-db.timestream", "ts"], ["elasticache-purpose-built-db.elasticache-redis-vs-memcached", "ec"], ["elasticache-purpose-built-db.dax-dynamodb-only", "dax"], ["elasticache-purpose-built-db.elasticache-multi-az-failover", "ec"], ["elasticache-purpose-built-db.elasticache-global-datastore", "ec"], ["elasticache-purpose-built-db.documentdb-global-cluster", "docdb"], ["elasticache-purpose-built-db.cache-requires-application-change", "ec"], ["elasticache-purpose-built-db.elasticache-not-a-durable-store", "ec"], ["elasticache-purpose-built-db.dax-encryption-at-rest", "dax"]],
  "ec2-autoscaling": [["ec2-autoscaling.ec2", "ec2"], ["ec2-autoscaling.ami-and-launch-template", "img"], ["ec2-autoscaling.ec2-image-builder", "img"], ["ec2-autoscaling.memory-optimized-instance-family", "fam"], ["ec2-autoscaling.gpu-instance-family", "fam"], ["ec2-autoscaling.reserved-instance-types", "buy"], ["ec2-autoscaling.spot-workload-fit", "buy"], ["ec2-autoscaling.scheduled-scaling", "pol"], ["ec2-autoscaling.target-tracking-vs-simple-scaling", "pol"], ["ec2-autoscaling.predictive-scaling", "pol"], ["ec2-autoscaling.spot-allocation-strategy", "spot"], ["ec2-autoscaling.asg-instance-type-override", "spot"], ["ec2-autoscaling.asg-on-demand-base-capacity", "spot"], ["ec2-autoscaling.warm-pool", "ops"], ["ec2-autoscaling.asg-single-instance-self-healing", "ops"], ["ec2-autoscaling.elb-health-check-drives-asg-replacement", "ops"], ["ec2-autoscaling.enhanced-networking", "fam"], ["ec2-autoscaling.parallelcluster", "hpc"]],
  "elastic-load-balancing": [["elastic-load-balancing.elb", "elb"], ["elastic-load-balancing.gateway-load-balancer", "gwlb"], ["elastic-load-balancing.alb-l7-vs-nlb-l4", "*"], ["elastic-load-balancing.alb-routing-conditions", "alb"], ["elastic-load-balancing.nlb-tls-listener", "nlb"], ["elastic-load-balancing.nlb-udp-listener", "nlb"], ["elastic-load-balancing.nlb-ip-targets", "nlb"], ["elastic-load-balancing.alb-cookie-stickiness", "alb"], ["elastic-load-balancing.internal-load-balancer", "common"], ["elastic-load-balancing.sticky-session-tradeoff", "alb"], ["elastic-load-balancing.alb-least-outstanding-requests", "alb"], ["elastic-load-balancing.alb-target-group-independent-scaling", "alb"], ["elastic-load-balancing.alb-listener-rule-fixed-response", "alb"], ["elastic-load-balancing.load-balancer-idle-timeout", "common"], ["elastic-load-balancing.end-to-end-encryption-behind-alb", "common"], ["elastic-load-balancing.gwlb-endpoint-cross-account-inspection", "gwlb"]],
  "cloudfront-global-accelerator": [["cloudfront-global-accelerator.cloudfront", "cf"], ["cloudfront-global-accelerator.cloudfront-alb-origin", "cf"], ["cloudfront-global-accelerator.cloudfront-multiple-origins", "cf"], ["cloudfront-global-accelerator.cloudfront-onprem-origin", "cf"], ["cloudfront-global-accelerator.global-accelerator", "ga"], ["cloudfront-global-accelerator.global-accelerator-static-ip", "ga"], ["cloudfront-global-accelerator.global-accelerator-endpoints", "ga"], ["cloudfront-global-accelerator.edge-keyword", "edge"], ["cloudfront-global-accelerator.lambda-at-edge", "edge"], ["cloudfront-global-accelerator.cloudfront-functions", "edge"], ["cloudfront-global-accelerator.global-accelerator-protocols", "ga"], ["cloudfront-global-accelerator.cloudfront-reduces-data-transfer-cost", "*"], ["cloudfront-global-accelerator.global-accelerator-vs-dns-failover", "ga"], ["cloudfront-global-accelerator.cloudfront-signed-url", "cf"], ["cloudfront-global-accelerator.cloudfront-signed-cookie", "cf"], ["cloudfront-global-accelerator.cloudfront-geo-restriction", "cf"], ["cloudfront-global-accelerator.cloudfront-field-level-encryption", "cf"], ["cloudfront-global-accelerator.lambda-at-edge-origin-selection-by-viewer-location", "edge"], ["cloudfront-global-accelerator.lambda-at-edge-response-compression", "edge"], ["cloudfront-global-accelerator.cloudfront-price-class", "cf"], ["cloudfront-global-accelerator.cloudfront-ttl", "cf"], ["cloudfront-global-accelerator.cloudfront-s3-upload-with-oac", "cf"], ["cloudfront-global-accelerator.cloudfront-alb-origin-access-restriction", "cf"], ["cloudfront-global-accelerator.cloudfront-functions-no-external-calls", "edge"]],
  "lambda": [["lambda.lambda", "base"], ["lambda.lambda-function-url", "inv"], ["lambda.lambda-function-url-iam-auth", "inv"], ["lambda.lambda-vpc-access", "net"], ["lambda.lambda-container-image", "pkg"], ["lambda.lambda-invocation-types", "inv"], ["lambda.lambda-memory-cpu-proportional", "mem"], ["lambda.lambda-reserved-concurrency", "conc"], ["lambda.lambda-provisioned-concurrency-autoscaling", "conc"], ["lambda.lambda-concurrency-limit-throttling", "conc"], ["lambda.lambda-kinesis-event-source", "inv"], ["lambda.lambda-snapstart", "conc"], ["lambda.lambda-memory-ceiling", "mem"], ["lambda.lambda-layer-size-limit", "pkg"], ["lambda.lambda-efs-mount", "pkg"], ["lambda.lambda-version-alias-config-freeze", "ver"], ["lambda.lambda-execution-role-logs", "perm"], ["lambda.serverless-runtime-no-os-access", "*os"]],
  "ecs-eks-fargate": [["ecs-eks-fargate.ecs", "ecs"], ["ecs-eks-fargate.eks", "eks"], ["ecs-eks-fargate.ecr-image-scan-on-push", "ecr"], ["ecs-eks-fargate.aws-batch", "batch"], ["ecs-eks-fargate.elastic-beanstalk", "eb"], ["ecs-eks-fargate.app2container", "a2c"], ["ecs-eks-fargate.eks-compute-options", "eks"], ["ecs-eks-fargate.fargate-no-time-limit", "far"], ["ecs-eks-fargate.fargate-spot", "far"], ["ecs-eks-fargate.batch-fargate-compute-environment", "batch"], ["ecs-eks-fargate.eks-fargate-pod-isolation", "eks"], ["ecs-eks-fargate.eks-cluster-autoscaler", "eks"], ["ecs-eks-fargate.eks-aws-load-balancer-controller", "eks"], ["ecs-eks-fargate.eks-connector", "eks"], ["ecs-eks-fargate.eks-anywhere", "eks"], ["ecs-eks-fargate.ecs-task-role", "ecs"], ["ecs-eks-fargate.ecs-task-role-vs-task-execution-role", "ecs"], ["ecs-eks-fargate.eks-irsa", "eks"], ["ecs-eks-fargate.ecs-awsvpc-mode", "ecs"], ["ecs-eks-fargate.ecs-task-placement-strategy", "ecs"], ["ecs-eks-fargate.fargate-per-second-billing", "far"], ["ecs-eks-fargate.fargate-efs-mount", "far"], ["ecs-eks-fargate.eks-secrets-kms-encryption", "eks"]],
  "api-gateway-step-functions": [["api-gateway-step-functions.api-gateway", "api"], ["api-gateway-step-functions.step-functions", "sf"], ["api-gateway-step-functions.step-functions-features", "sf"], ["api-gateway-step-functions.amplify", "amp"], ["api-gateway-step-functions.api-gateway-jwt-authorizer", "api"], ["api-gateway-step-functions.api-gateway-rest-vs-http-timeout", "api"], ["api-gateway-step-functions.api-gateway-rest-only-features", "api"], ["api-gateway-step-functions.api-gateway-websocket-api", "api"], ["api-gateway-step-functions.api-gateway-api-key-not-auth", "api"], ["api-gateway-step-functions.api-gateway-resource-policy", "api"], ["api-gateway-step-functions.api-gateway-endpoint-types", "api"], ["api-gateway-step-functions.api-gateway-behind-cloudfront", "api"], ["api-gateway-step-functions.api-gateway-lambda-proxy-integration", "api"], ["api-gateway-step-functions.api-gateway-aws-service-integration", "api"], ["api-gateway-step-functions.step-functions-long-running-workflow", "sf"], ["api-gateway-step-functions.step-functions-express-workflow", "sf"], ["api-gateway-step-functions.step-functions-map-state", "sf"], ["api-gateway-step-functions.api-gateway-custom-domain-name", "api"], ["api-gateway-step-functions.api-gateway-mapping-template-limits", "api"], ["api-gateway-step-functions.api-gateway-ip-restriction-by-resource-policy", "api"]],
  "sqs-sns-eventbridge": [["sqs-sns-eventbridge.sqs", "sqs"], ["sqs-sns-eventbridge.sns", "sns"], ["sqs-sns-eventbridge.eventbridge", "eb"], ["sqs-sns-eventbridge.eventbridge-scheduler", "eb"], ["sqs-sns-eventbridge.amazon-mq", "mq"], ["sqs-sns-eventbridge.ses", "ses"], ["sqs-sns-eventbridge.dead-letter-queue", "sqs"], ["sqs-sns-eventbridge.sns-is-not-a-queue", "ss"], ["sqs-sns-eventbridge.sns-sqs-fanout-per-consumer", "ss"], ["sqs-sns-eventbridge.eventbridge-vs-step-functions", "eb"], ["sqs-sns-eventbridge.eventbridge-ordering-and-retention", "eb"], ["sqs-sns-eventbridge.eventbridge-event-pattern-vs-polling", "eb"], ["sqs-sns-eventbridge.eventbridge-event-bus-types", "eb"], ["sqs-sns-eventbridge.eventbridge-pipes", "eb"], ["sqs-sns-eventbridge.eventbridge-api-destination", "eb"], ["sqs-sns-eventbridge.eventbridge-private-api-target", "eb"], ["sqs-sns-eventbridge.eventbridge-resource-change-rule", "eb"], ["sqs-sns-eventbridge.sqs-details", "sqs"], ["sqs-sns-eventbridge.sns-fifo-topic", "sns"], ["sqs-sns-eventbridge.ses-inbound-email-receiving", "ses"], ["sqs-sns-eventbridge.sqs-queue-depth-scaling", "sqs"], ["sqs-sns-eventbridge.sqs-batch-and-polling", "sqs"], ["sqs-sns-eventbridge.sqs-visibility-timeout-vs-processing-time", "sqs"], ["sqs-sns-eventbridge.sqs-message-size-limit", "sqs"], ["sqs-sns-eventbridge.sqs-fifo-message-group-id", "sqs"], ["sqs-sns-eventbridge.sqs-fifo-deduplication-id", "sqs"], ["sqs-sns-eventbridge.sqs-content-based-deduplication", "sqs"], ["sqs-sns-eventbridge.sns-no-message-body-rewrite", "sns"], ["sqs-sns-eventbridge.sqs-queue-policy", "sqs"], ["sqs-sns-eventbridge.cross-account-sns-to-sqs-queue-policy", "ss"], ["sqs-sns-eventbridge.sqs-encryption-and-consumer-kms-permission", "sqs"], ["sqs-sns-eventbridge.sns-encrypted-topic-publish-permissions", "sns"], ["sqs-sns-eventbridge.sqs-vpc-endpoint-and-queue-policy", "sqs"]],
  "backup-disaster-recovery": [["backup-disaster-recovery.backup", "bk"], ["backup-disaster-recovery.elastic-disaster-recovery", "drs"], ["backup-disaster-recovery.backup-and-restore-dr", "dr"], ["backup-disaster-recovery.warm-standby-for-low-rto", "dr"], ["backup-disaster-recovery.backup-long-term-retention", "bk"], ["backup-disaster-recovery.backup-ec2-resource-assignment", "bk"], ["backup-disaster-recovery.organizations-backup-policy", "bk"], ["backup-disaster-recovery.backup-cross-account-copy", "bk"], ["backup-disaster-recovery.backup-s3-continuous-backup", "bk"], ["backup-disaster-recovery.backup-restore-testing-plan", "bk"], ["backup-disaster-recovery.backup-audit-manager", "bk"]],
  "vpc-networking": [["vpc-networking.vpc-subnet", "vpc"], ["vpc-networking.internet-gateway", "igw"], ["vpc-networking.egress-only-igw", "igw"], ["vpc-networking.nat-gateway", "nat"], ["vpc-networking.vpc-endpoint", "ep"], ["vpc-networking.privatelink", "pl"], ["vpc-networking.vpc-peering", "peer"], ["vpc-networking.vpc-flow-logs", "fl"], ["vpc-networking.comparison", "*"], ["vpc-networking.nat-gateway-traffic-uses-public-endpoints", "*"], ["vpc-networking.endpoint-pricing", "ep"], ["vpc-networking.privatelink-endpoint-service", "pl"], ["vpc-networking.nat-instance", "*"], ["vpc-networking.nat-gateway-per-az", "nat"], ["vpc-networking.internet-gateway-is-not-per-az", "*"], ["vpc-networking.nat-gateway-count-by-environment", "nat"], ["vpc-networking.nat-gateway-elastic-ip", "nat"], ["vpc-networking.vpc-endpoint-policy", "ep"], ["vpc-networking.vpc-peering-scaling-limit", "peer"], ["vpc-networking.s3-is-regional", "ep"]],
  "security-groups-nacl": [["security-groups-nacl.security-group", "sg"], ["security-groups-nacl.nacl", "nacl"], ["security-groups-nacl.security-group-stateful-vs-nacl-stateless", "*"], ["security-groups-nacl.web-acl-vs-nacl", "*"], ["security-groups-nacl.security-group-referencing", "sg"], ["security-groups-nacl.nacl-rule-limit", "nacl"], ["security-groups-nacl.nacl-deny-at-source-subnet", "nacl"], ["security-groups-nacl.alb-security-group-outbound-and-health-check-port", "sg"], ["security-groups-nacl.nlb-security-group", "sg"]],
  "hybrid-connectivity": [["hybrid-connectivity.site-to-site-vpn", "vpn"], ["hybrid-connectivity.client-vpn", "cvpn"], ["hybrid-connectivity.direct-connect", "dx"], ["hybrid-connectivity.virtual-private-gateway", "dx"], ["hybrid-connectivity.access-terms", "vpn"], ["hybrid-connectivity.transit-gateway", "tgw"], ["hybrid-connectivity.direct-connect-gateway", "dx"], ["hybrid-connectivity.region-attached-edge-options", "edge"], ["hybrid-connectivity.onprem-connectivity-heuristic", "*"], ["hybrid-connectivity.vpn-vs-direct-connect", "*"], ["hybrid-connectivity.per-vpc-vpn-for-isolation", "*"], ["hybrid-connectivity.transit-gateway-cross-region-peering", "tgw"], ["hybrid-connectivity.onprem-access-via-interface-endpoint", "hyb"], ["hybrid-connectivity.data-locality-cost", "hyb"], ["hybrid-connectivity.outposts-data-residency", "edge"], ["hybrid-connectivity.direct-connect-caveats", "dx"], ["hybrid-connectivity.direct-connect-resiliency", "dx"], ["hybrid-connectivity.direct-connect-vif-types", "dx"], ["hybrid-connectivity.centralized-onprem-egress", "hyb"]],
  "route53": [["route53.route53", "base"], ["route53.routing-policies", "rp"], ["route53.resolver", "res"], ["route53.private-hosted-zone", "hz"], ["route53.route53-zone-file-import", "hz"], ["route53.route53-failover-routing", "rp"], ["route53.multi-region-failover-for-region-outage", "rp"], ["route53.latency-record-for-non-aws-endpoint", "rp"], ["route53.route53-alias-record", "hz"], ["route53.private-hosted-zone-vpc-only", "hz"], ["route53.route53-resolver-forward-rule", "res"], ["route53.multivalue-answer-details", "rp"], ["route53.route53-query-logging", "log"]],
  "emr-glue-athena": [["emr-glue-athena.emr", "emr"], ["emr-glue-athena.emr-node-types", "emr"], ["emr-glue-athena.spark", "spark"], ["emr-glue-athena.glue", "glue"], ["emr-glue-athena.glue-crawler", "glue"], ["emr-glue-athena.glue-databrew", "glue"], ["emr-glue-athena.athena", "ath"], ["emr-glue-athena.lake-formation", "lf"], ["emr-glue-athena.emr-transient-cluster", "emr"], ["emr-glue-athena.emr-managed-scaling", "emr"], ["emr-glue-athena.glue-etl-with-per-customer-kms-key", "glue"], ["emr-glue-athena.athena-encrypted-and-pay-per-query", "ath"], ["emr-glue-athena.athena-federated-query", "ath"], ["emr-glue-athena.log-storage-s3-athena", "ath"], ["emr-glue-athena.lake-formation-blueprint-and-athena", "lf"], ["emr-glue-athena.lake-formation-lf-tags", "lf"], ["emr-glue-athena.emr-node-instance-family-choice", "emr"], ["emr-glue-athena.emr-runtime-role", "emr"], ["emr-glue-athena.emr-security-configuration", "emr"], ["emr-glue-athena.parquet-columnar-format", "pq"]],
  "kinesis-streaming": [["kinesis-streaming.kinesis-data-streams", "kds"], ["kinesis-streaming.data-firehose", "fh"], ["kinesis-streaming.managed-service-apache-flink", "flink"], ["kinesis-streaming.kinesis-video-streams", "kvs"], ["kinesis-streaming.msk", "msk"], ["kinesis-streaming.streaming-services-comparison", "*"], ["kinesis-streaming.flink-kinesis-source-sink", "flink"], ["kinesis-streaming.firehose-lambda-transformation", "fh"], ["kinesis-streaming.firehose-format-conversion", "fh"], ["kinesis-streaming.kinesis-retention-and-fanout", "kds"], ["kinesis-streaming.kinesis-client-library", "kds"], ["kinesis-streaming.msk-kafka-connect", "msk"], ["kinesis-streaming.kinesis-record-size-limit", "kds"], ["kinesis-streaming.kinesis-partition-key-hot-shard", "kds"], ["kinesis-streaming.kinesis-capacity-mode", "kds"], ["kinesis-streaming.firehose-buffering", "fh"]],
  "redshift-opensearch-quicksight": [["redshift-opensearch-quicksight.redshift", "rs"], ["redshift-opensearch-quicksight.redshift-spectrum", "rs"], ["redshift-opensearch-quicksight.opensearch-text-search", "os"], ["redshift-opensearch-quicksight.quicksight", "qs"], ["redshift-opensearch-quicksight.oltp-vs-olap", "rs"], ["redshift-opensearch-quicksight.athena-vs-redshift-workload", "rs"], ["redshift-opensearch-quicksight.redshift-hot-cold-split", "rs"], ["redshift-opensearch-quicksight.quicksight-ml-forecast", "qs"], ["redshift-opensearch-quicksight.redshift-concurrency-scaling", "rs"], ["redshift-opensearch-quicksight.redshift-copy-from-s3", "rs"], ["redshift-opensearch-quicksight.dynamodb-to-s3-analytics", "pipe"]],
  "cloudwatch-xray": [["cloudwatch-xray.cloudwatch", "cw"], ["cloudwatch-xray.x-ray", "xr"], ["cloudwatch-xray.performance-insight", "pi"], ["cloudwatch-xray.amazon-managed-grafana", "graf"], ["cloudwatch-xray.cloudwatch-network-monitor", "cw"], ["cloudwatch-xray.cloudwatch-container-insights", "cw"], ["cloudwatch-xray.log-analysis-options", "cw"], ["cloudwatch-xray.performance-insights-rightsizing", "pi"], ["cloudwatch-xray.cloudwatch-agent-memory-metric", "cw"], ["cloudwatch-xray.ec2-detailed-monitoring", "cw"], ["cloudwatch-xray.cloudwatch-alarm-state-change-event", "cw"]],
  "secrets-encryption": [["secrets-encryption.secrets-manager", "sm"], ["secrets-encryption.parameter-store", "ps"], ["secrets-encryption.kms", "kms"], ["secrets-encryption.acm", "acm"], ["secrets-encryption.cloudhsm", "hsm"], ["secrets-encryption.secrets-manager-vs-parameter-store", "smps"], ["secrets-encryption.rotation-heuristic", "smps"], ["secrets-encryption.kms-key-types-by-management", "kms"], ["secrets-encryption.kms-multi-region-key", "kms"], ["secrets-encryption.kms-imported-key-material", "kms"], ["secrets-encryption.kms-cloudhsm-key-store", "hsm"], ["secrets-encryption.kms-key-per-tenant", "kms"], ["secrets-encryption.acm-dns-validation", "acm"], ["secrets-encryption.secrets-manager-batch-get-secret-value", "sm"], ["secrets-encryption.kms-automatic-key-rotation", "kms"], ["secrets-encryption.kms-symmetric-vs-asymmetric-rotation", "kms"], ["secrets-encryption.imported-key-material-rotation", "kms"], ["secrets-encryption.lambda-env-var-kms", "kms"], ["secrets-encryption.acm-cloudfront-region", "acm"], ["secrets-encryption.acm-expiration-event", "acm"]],
  "waf-shield": [["waf-shield.waf", "waf"], ["waf-shield.shield", "shield"], ["waf-shield.cloudfront", "waf"], ["waf-shield.firewall-manager", "fm"], ["waf-shield.waf-attach-targets", "waf"], ["waf-shield.waf-rule-types", "waf"], ["waf-shield.waf-managed-rule-groups", "waf"], ["waf-shield.waf-rate-based-rule", "waf"], ["waf-shield.waf-bot-control", "waf"], ["waf-shield.shield-standard-network-layer", "shield"], ["waf-shield.shield-advanced-drt", "shield"], ["waf-shield.shield-advanced-protection-group", "shield"], ["waf-shield.waf-body-inspection-size-limit", "waf"], ["waf-shield.waf-web-acl-region-must-match-rest-api", "waf"], ["waf-shield.waf-logging-to-firehose", "waf"]],
  "guardduty-macie-inspector": [["guardduty-macie-inspector.guardduty", "gd"], ["guardduty-macie-inspector.macie", "mac"], ["guardduty-macie-inspector.amazon-inspector", "insp"], ["guardduty-macie-inspector.security-hub", "sh"], ["guardduty-macie-inspector.security-service-lineup", "*"], ["guardduty-macie-inspector.guardduty-db-login", "gd"], ["guardduty-macie-inspector.macie-automated-discovery", "mac"], ["guardduty-macie-inspector.inspector-scans-ecr-images", "insp"], ["guardduty-macie-inspector.macie-delegated-administrator", "mac"], ["guardduty-macie-inspector.guardduty-finding-to-eventbridge", "gd"], ["guardduty-macie-inspector.macie-finding-to-eventbridge", "mac"]],
  "iam-permissions": [["iam-permissions.iam", "base"], ["iam-permissions.instance-profile", "role"], ["iam-permissions.iam-group-policy-attachment", "grp"], ["iam-permissions.iam-roles-anywhere", "role"], ["iam-permissions.iam-access-analyzer", "aa"], ["iam-permissions.network-access-analyzer", "aa"], ["iam-permissions.least-privilege", "pol"], ["iam-permissions.abac", "pol"], ["iam-permissions.permissions-boundary", "pol"], ["iam-permissions.cross-account-iam-role", "role"], ["iam-permissions.iam-group-users-only", "grp"], ["iam-permissions.iam-user-is-account-scoped", "grp"], ["iam-permissions.iam-explicit-deny-precedence", "pol"], ["iam-permissions.iam-notaction-deny", "pol"], ["iam-permissions.iam-requested-region-condition", "pol"], ["iam-permissions.access-analyzer-delegated-administrator", "aa"], ["iam-permissions.root-user-multiple-mfa", "root"], ["iam-permissions.root-user-cannot-be-disabled", "root"]],
  "identity-federation": [["identity-federation.identity-center", "ic"], ["identity-federation.sts", "sts"], ["identity-federation.cognito", "cog"], ["identity-federation.aws-directory-service", "ds"], ["identity-federation.sts-assume-role", "sts"], ["identity-federation.identity-center-external-idp", "ic"], ["identity-federation.cognito-pools", "cog"], ["identity-federation.cognito-social-idp-federation", "cog"], ["identity-federation.custom-identity-broker-for-non-saml", "fed"], ["identity-federation.identity-center-permission-set", "ic"], ["identity-federation.saml-federation-role-to-ad-group-mapping", "fed"]],
  "organizations-cloudtrail-config": [["organizations-cloudtrail-config.organizations-scp", "org"], ["organizations-cloudtrail-config.cloudtrail", "ct"], ["organizations-cloudtrail-config.cloudtrail-lake", "ct"], ["organizations-cloudtrail-config.aws-config", "cfg"], ["organizations-cloudtrail-config.audit-manager", "am"], ["organizations-cloudtrail-config.organizational-unit", "org"], ["organizations-cloudtrail-config.organizations-tag-policy", "org"], ["organizations-cloudtrail-config.organizations-consolidated-billing", "org"], ["organizations-cloudtrail-config.cloudtrail-data-events", "ct"], ["organizations-cloudtrail-config.config-configuration-recorder", "cfg"], ["organizations-cloudtrail-config.scp-attachment-targets", "org"], ["organizations-cloudtrail-config.scp-condition-exception", "org"], ["organizations-cloudtrail-config.cloudtrail-log-file-validation", "ct"], ["organizations-cloudtrail-config.config-conformance-pack", "cfg"], ["organizations-cloudtrail-config.config-custom-rule", "cfg"], ["organizations-cloudtrail-config.config-rule-remediation", "cfg"]],
  "cost-management": [["cost-management.savings-plan", "commit"], ["cost-management.aws-budgets", "bud"], ["cost-management.cost-explorer", "vis"], ["cost-management.cost-anomaly-detection", "cad"], ["cost-management.cost-and-usage-report", "cur"], ["cost-management.billing-and-cost-management", "vis"], ["cost-management.trusted-advisor", "adv"], ["cost-management.compute-optimizer", "adv"], ["cost-management.savings-plan-details", "commit"], ["cost-management.savings-plan-baseline-vs-spike", "commit"], ["cost-management.rds-reserved-instance", "commit"], ["cost-management.on-demand-capacity-reservation", "commit"], ["cost-management.cost-allocation-tag-activation", "vis"], ["cost-management.cost-allocation-tag-activation-in-management-account", "vis"], ["cost-management.budget-actions", "bud"], ["cost-management.budget-forecasted-alert", "bud"], ["cost-management.compute-optimizer-ebs-recommendations", "adv"]],
  "governance-iac": [["governance-iac.cloudformation", "cfn"], ["governance-iac.service-catalog", "sc"], ["governance-iac.control-tower-landing-zone", "ct"], ["governance-iac.resource-access-manager", "ram"], ["governance-iac.workload-discovery", "wd"], ["governance-iac.control-tower-controls", "ct"], ["governance-iac.cloudformation-drift-detection", "cfn"]],
  "systems-manager": [["systems-manager.ssm-run-command", "ssm"], ["systems-manager.appconfig", "appc"], ["systems-manager.ssm-session-manager", "ssm"], ["systems-manager.ec2-instance-connect-endpoint", "eic"], ["systems-manager.ssm-patch-manager", "ssm"], ["systems-manager.ssm-managed-instance-core-policy", "ssm"], ["systems-manager.ssm-inventory", "ssm"]],
  "ai-ml-services": [["ai-ml-services.sagemaker", "sm"], ["ai-ml-services.media-ai-service-lineup", "lineup"], ["ai-ml-services.comprehend", "comp"], ["ai-ml-services.amazon-lex", "lex"], ["ai-ml-services.sagemaker-autopilot", "sm"], ["ai-ml-services.rekognition-content-moderation", "*"]],
}

const step = Number(process.argv[2])
if (!Number.isInteger(step) || step < 0 || step >= STEPS.length) {
  console.log(`사용법: node phases/34-service-block-order/verify-order.mjs <0..${STEPS.length - 1}>`)
  process.exit(2)
}

const problems = []
const topicsRaw = read('src/data/topics.json')
const baselineRaw = read('scripts/topics-baseline.json')
const topics = JSON.parse(topicsRaw)
const baseline = JSON.parse(baselineRaw)

// 1. 문항 파일
if (sha(readFileSync(join(ROOT, 'src/data/questions.json'))) !== BASE.questions) {
  problems.push('src/data/questions.json이 착수 시점과 다르다 — 문항은 이 phase에서 바꾸지 않는다')
}

// 2. 개념 내용·소속·주제 메타데이터 (순서와 무관)
const canon = topics.map((t) => ({ id: t.id, title: t.title, importance: t.importance, sourcePages: t.sourcePages, keys: Object.keys(t), concepts: [...t.concepts].sort(byId) }))
if (sha(JSON.stringify(canon)) !== BASE.content) {
  problems.push('topics.json의 개념 내용·주제 소속·주제 메타데이터 중 무엇인가가 착수 시점과 다르다 — 순서 말고는 바꾸지 않는다')
}

// 3. 줄 단위 — 줄 자리와 끝 쉼표 말고는 바뀐 것이 없다
if (lineMultiset(topicsRaw) !== BASE.topicsLines) {
  problems.push('topics.json의 줄 구성이 착수 시점과 다르다 — 줄을 옮기고 끝 쉼표만 고쳐야 한다(재직렬화·글자 수정 금지)')
}

// 4. 누락·중복
const allIds = topics.flatMap((t) => t.concepts.map((c) => c.id))
if (allIds.length !== 618) problems.push(`개념 수가 618이 아니라 ${allIds.length}이다`)
if (new Set(allIds).size !== allIds.length) problems.push('개념 id가 중복됐다')

// 5. 주제별 순서 — 누구의 순서가 바뀌었나, 왕복은 몇 번인가
const expected = new Set(STEPS.slice(0, step + 1).flat())
const returnsOf = (labels) => {
  const seen = new Set()
  let prev = null
  let count = 0
  for (const l of labels) {
    if (l.startsWith('*')) continue
    if (l !== prev && seen.has(l)) count += 1
    seen.add(l)
    prev = l
  }
  return count
}
const report = []
for (const t of topics) {
  const orig = ORIGINAL[t.id]
  if (!orig) { problems.push(`착수 시점에 없던 주제 ${t.id}`); continue }
  const origIds = orig.map(([id]) => id)
  const ids = t.concepts.map((c) => c.id)
  if (JSON.stringify([...ids].sort()) !== JSON.stringify([...origIds].sort())) {
    problems.push(`${t.id}의 개념 id 집합이 착수 시점과 다르다`)
    continue
  }
  const changed = ids.some((id, i) => id !== origIds[i])
  if (changed && !expected.has(t.id)) problems.push(`${t.id}의 순서가 바뀌었는데 step ${step}까지의 명세에 없는 주제다`)
  if (!changed && expected.has(t.id)) problems.push(`${t.id}는 step ${step}까지 재정렬해야 하는데 순서가 착수 시점 그대로다`)
  if (!changed) continue
  const label = Object.fromEntries(orig)
  const before = returnsOf(orig.map(([, l]) => l))
  const after = returnsOf(ids.map((id) => label[id]))
  const moved = ids.filter((id, i) => id !== origIds[i]).length
  report.push(`  ${after === 0 ? '✓' : '✗'} ${t.id.padEnd(32)} 자리 바뀐 개념 ${String(moved).padStart(2)}/${ids.length}  왕복 ${before} → ${after}`)
  if (after !== 0) problems.push(`${t.id}에 서비스 왕복이 ${after}번 남았다`)
}

// 6. 구조 스냅샷 — 개념 항목 순서만 바뀌었고, 순서가 topics.json과 같다
const baselineCanon = { ...baseline, topics: baseline.topics.map((t) => ({ ...t, concepts: [...t.concepts].sort(byId) })) }
if (sha(JSON.stringify(baselineCanon)) !== BASE.baselineCanon) {
  problems.push('topics-baseline.json에서 개념 항목 순서 말고 바뀐 것이 있다(id·name·메타데이터·questionsSha256·conceptLineCount·note)')
}
if (lineMultiset(baselineRaw) !== BASE.baselineLines) {
  problems.push('topics-baseline.json의 줄 구성이 달라졌다 — JSON.stringify(obj, null, 1) + "\\n" 형식을 지켜라')
}
baseline.topics.forEach((bt, i) => {
  const t = topics[i]
  if (!t || t.id !== bt.id) return
  if (JSON.stringify(bt.concepts.map((c) => c.id)) !== JSON.stringify(t.concepts.map((c) => c.id))) {
    problems.push(`topics-baseline.json의 ${bt.id} 개념 순서가 topics.json과 다르다`)
  }
})

console.log(`phase 34 verify-order — step ${step} (재정렬 누적 ${expected.size}개 주제)`)
if (report.length) console.log(report.join('\n'))
else console.log('  순서가 바뀐 주제 없음')
if (problems.length) {
  for (const p of problems) console.log(`✗ ${p}`)
  console.log(`\n위반 ${problems.length}건`)
  process.exit(1)
}
console.log('✓ 문항 해시·개념 내용 해시·줄 구성·스냅샷이 착수 시점과 같고, 바뀐 것은 명세된 주제의 개념 순서뿐이다')
